//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcesarDirectorio.Entity.CargueInformacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APPSEVIALCargueInformacionEntities : DbContext
    {
        public APPSEVIALCargueInformacionEntities()
            : base("name=APPSEVIALCargueInformacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP011_DarTipoArchivo_Result> SP011_DarTipoArchivo(ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP011_DarTipoArchivo_Result>("SP011_DarTipoArchivo", codigoRpta, mensajeRpta);
        }
    
        public virtual int SP012_RegistrarArchivo(Nullable<int> tipoArchivo, string nombreArchivo, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var tipoArchivoParameter = tipoArchivo.HasValue ?
                new ObjectParameter("tipoArchivo", tipoArchivo) :
                new ObjectParameter("tipoArchivo", typeof(int));
    
            var nombreArchivoParameter = nombreArchivo != null ?
                new ObjectParameter("nombreArchivo", nombreArchivo) :
                new ObjectParameter("nombreArchivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP012_RegistrarArchivo", tipoArchivoParameter, nombreArchivoParameter, codigoRpta, mensajeRpta);
        }
    }
}
