//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sevial.API2.Entity.Parametro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APPSEVIALEntities2 : DbContext
    {
        public APPSEVIALEntities2()
            : base("name=APPSEVIALParametro")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP005_DarListaCategoria_Result> SP005_DarListaCategoria(string aliasUsuario, string nomCategoria, string filtro, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var nomCategoriaParameter = nomCategoria != null ?
                new ObjectParameter("nomCategoria", nomCategoria) :
                new ObjectParameter("nomCategoria", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP005_DarListaCategoria_Result>("SP005_DarListaCategoria", aliasUsuarioParameter, nomCategoriaParameter, filtroParameter, codigoRpta, mensajeRpta);
        }
    
        public virtual ObjectResult<SP030_ListarDepartamentales_Result> SP030_ListarDepartamentales(string aliasUsuario, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP030_ListarDepartamentales_Result>("SP030_ListarDepartamentales", aliasUsuarioParameter, codigoRpta, mensajeRpta);
        }
    
        public virtual ObjectResult<SP031_ListarMunDisponiblesDptal_Result> SP031_ListarMunDisponiblesDptal(string aliasUsuario, Nullable<int> departamental, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var departamentalParameter = departamental.HasValue ?
                new ObjectParameter("departamental", departamental) :
                new ObjectParameter("departamental", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP031_ListarMunDisponiblesDptal_Result>("SP031_ListarMunDisponiblesDptal", aliasUsuarioParameter, departamentalParameter, codigoRpta, mensajeRpta);
        }
    
        public virtual ObjectResult<SP032_ListarMunicipiosDptal_Result> SP032_ListarMunicipiosDptal(string aliasUsuario, Nullable<int> departamental, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var departamentalParameter = departamental.HasValue ?
                new ObjectParameter("departamental", departamental) :
                new ObjectParameter("departamental", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP032_ListarMunicipiosDptal_Result>("SP032_ListarMunicipiosDptal", aliasUsuarioParameter, departamentalParameter, codigoRpta, mensajeRpta);
        }
    
        public virtual int SP033_EditarDptal(string aliasUsuario, Nullable<int> departamental, string nombre, string divipola, string listaMunicipios, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var departamentalParameter = departamental.HasValue ?
                new ObjectParameter("departamental", departamental) :
                new ObjectParameter("departamental", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var divipolaParameter = divipola != null ?
                new ObjectParameter("divipola", divipola) :
                new ObjectParameter("divipola", typeof(string));
    
            var listaMunicipiosParameter = listaMunicipios != null ?
                new ObjectParameter("listaMunicipios", listaMunicipios) :
                new ObjectParameter("listaMunicipios", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP033_EditarDptal", aliasUsuarioParameter, departamentalParameter, nombreParameter, divipolaParameter, listaMunicipiosParameter, codigoRpta, mensajeRpta);
        }
    }
}
