//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sevial.API2.Entity.Parametro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APPSEVIALEntities2 : DbContext
    {
        public APPSEVIALEntities2()
            : base("name=APPSEVIALParametro")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP005_DarListaCategoria_Result> SP005_DarListaCategoria(string aliasUsuario, string nomCategoria, string filtro, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var nomCategoriaParameter = nomCategoria != null ?
                new ObjectParameter("nomCategoria", nomCategoria) :
                new ObjectParameter("nomCategoria", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP005_DarListaCategoria_Result>("SP005_DarListaCategoria", aliasUsuarioParameter, nomCategoriaParameter, filtroParameter, codigoRpta, mensajeRpta);
        }
    }
}
