//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sevial.API2.Entity.CargueInformacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APPSEVIALCargueInformacion : DbContext
    {
        public APPSEVIALCargueInformacion()
            : base("name=APPSEVIALCargueInformacion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP006_DarArchivosCargue_Result> SP006_DarArchivosCargue(string aliasUsuario, Nullable<int> idTipoCargue, Nullable<int> idEstadoCargue, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var idTipoCargueParameter = idTipoCargue.HasValue ?
                new ObjectParameter("idTipoCargue", idTipoCargue) :
                new ObjectParameter("idTipoCargue", typeof(int));
    
            var idEstadoCargueParameter = idEstadoCargue.HasValue ?
                new ObjectParameter("idEstadoCargue", idEstadoCargue) :
                new ObjectParameter("idEstadoCargue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP006_DarArchivosCargue_Result>("SP006_DarArchivosCargue", aliasUsuarioParameter, idTipoCargueParameter, idEstadoCargueParameter, codigoRpta, mensajeRpta);
        }
    
        public virtual int SP007_ProcesarArchivo(string aliasUsuario, string listaProcesar, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var listaProcesarParameter = listaProcesar != null ?
                new ObjectParameter("listaProcesar", listaProcesar) :
                new ObjectParameter("listaProcesar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP007_ProcesarArchivo", aliasUsuarioParameter, listaProcesarParameter, codigoRpta, mensajeRpta);
        }
    
        public virtual int SP013_IniciarProceso(string aliasUsuario, Nullable<int> tipoArchivo, Nullable<int> numArchivo, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var tipoArchivoParameter = tipoArchivo.HasValue ?
                new ObjectParameter("tipoArchivo", tipoArchivo) :
                new ObjectParameter("tipoArchivo", typeof(int));
    
            var numArchivoParameter = numArchivo.HasValue ?
                new ObjectParameter("numArchivo", numArchivo) :
                new ObjectParameter("numArchivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP013_IniciarProceso", aliasUsuarioParameter, tipoArchivoParameter, numArchivoParameter, codigoRpta, mensajeRpta);
        }
    }
}
