//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sevial.API2.Entity.Seguridad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APPSEVIALEntities : DbContext
    {
        public APPSEVIALEntities()
            : base("name=APPSEVIALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SEG_TB001_Usuario> SEG_TB001_Usuario { get; set; }
    
        public virtual ObjectResult<SP001_AutenticarUsuario_Result> SP001_AutenticarUsuario(string aliasUsuario, string clave, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP001_AutenticarUsuario_Result>("SP001_AutenticarUsuario", aliasUsuarioParameter, claveParameter, codigoRpta, mensajeRpta);
        }
    
        public virtual ObjectResult<SP002_DarModuloUsuario_Result> SP002_DarModuloUsuario(string aliasUsuario, ObjectParameter codigoRpta, ObjectParameter mensajeRpta)
        {
            var aliasUsuarioParameter = aliasUsuario != null ?
                new ObjectParameter("aliasUsuario", aliasUsuario) :
                new ObjectParameter("aliasUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP002_DarModuloUsuario_Result>("SP002_DarModuloUsuario", aliasUsuarioParameter, codigoRpta, mensajeRpta);
        }
    }
}
